# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion = "[44,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license = "Minecraft Mod Public License Japanese Transration"
# A URL to refer people to when problems occur with this mod
issueTrackerURL = "https://github.com/Korea-Minecraft-Forum/CocoaInput/issues"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId = "cocoainput" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${version} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version = "${version}" #mandatory
# A display name for the mod
displayName = "CocoaInput" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://axer.jp/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile = "icon.png" #optional
# A text field displayed in the mod UI
credits="This mod uses JavaNativeAccess(Apache License2)." #optional
# A text field displayed in the mod UI
authors="Axeryok, LemonCaramel" #optional
# The description text for the mod (multi line!) (#mandatory)
description = '''
Support IME input on macOS, Windows, X11(Linux).
'''

# A dependency
[[dependencies.cocoainput]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
side = "CLIENT"

[[dependencies.cocoainput]]
modId = "minecraft"
mandatory = true
versionRange = "1.19.3"
side = "CLIENT"
